"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isDigit = exports.getDigit = exports.delSpace = exports.dotToComma = exports.commaToDot = exports.isComma = exports.isDot = exports.isDotComma = void 0;
const isDotComma = (str) => /[,.]/g.test(str);
exports.isDotComma = isDotComma;
const isDot = (str) => /\./g.test(str);
exports.isDot = isDot;
const isComma = (str) => /,/g.test(str);
exports.isComma = isComma;
const commaToDot = (str) => str.replace(/\,/g, `.`);
exports.commaToDot = commaToDot;
const dotToComma = (str) => str.replace(/\./g, `,`);
exports.dotToComma = dotToComma;
const delSpace = (str) => str.replace(/\s/g, ``);
exports.delSpace = delSpace;
const getDigit = (str) => str.replace(/\D/g, ``);
exports.getDigit = getDigit;
const isDigit = (str) => /\d/g.test(str);
exports.isDigit = isDigit;
